import { LocationList } from "../../components";

const LocationIter = ({}) => {
  const storeList = {
    BANDUNG: [
      "HAUS! - DIPATIUKUR",
      "HAUS! - GEGER KALONG",
      "HAUS! - UJUNG BERUNG",
      "HAUS! - CIJERAH",
      "HAUS! - KIARA CONDONG",
      "HAUS! - ANTAPANI",
      "HAUS! - CIKUTRA",
      "HAUS! - CIMAHI",
      "HAUS! - METRO",
      "HAUS! - CIBIRU",
      "HAUS! - BALEENDAH",
      "HAUS! - STT TELKOM",
      "HAUS! - BUAH BATU",
      "HAUS! - TAMAN KOPO INDAH",
      "HAUS! - CIBADUYUT",
      "HAUS! - PADALARANG",
      "HAUS! - CIUMBULEUIT",
      "HAUS! - RANCAEKEK",
      "HAUS! - CIMAHI 2",
    ],
    BEKASI: [
      "HAUS! - BINTARA",
      "HAUS! - JATIWARINGIN",
      "HAUS! - TAMBUN",
      "HAUS! - CAMAN",
      "HAUS! - PONDOK UNGU",
      "HAUS! - KARTINI",
      "HAUS! - HANKAM",
      "HAUS! - NUSANTARA",
      "HAUS! - RAWALUMBU",
      "HAUS! - CIBITUNG",
      "HAUS! - KARANG SATRIA",
      "HAUS! - PONDOK UNGU 2",
      "HAUS! - GALAXY",
      "HAUS! - HARAPAN INDAH",
      "HAUS! - KRANGGAN PERMAI",
      "HAUS! - NANGKA RAYA",
      "HAUS! - PURI GADING",
      "HAUS! - JATI KRAMAT RAYA",
      "HAUS! - PATRIOT",
      "HAUS! - PRAMUKA RAWALUMBU",
      "HAUS! - RADEN SANIM",
      "HAUS! - DUKUH ZAMBRUD",
      "HAUS! - MUCHTAR TABRANI",
      "HAUS! - MUTIARA GADING",
      "HAUS! - SUMBER ARTHA BINTARA",
      "HAUS! - KALIABANG",
      "HAUS! - KEMANG RAYA JATICEMPAKA",
      "HAUS! - PLASA CIBUBUR",
    ],
    BOGOR: [
      "HAUS! - CIKEAS",
      "HAUS! - AIR MANCUR",
      "HAUS! - EMPANG BOGOR",
      "HAUS! - KEBON PEDES",
      "HAUS! - MAWAR",
      "HAUS! - CIBINONG",
      "HAUS! - TAJUR",
      "HAUS! - DRAMAGA",
      "HAUS! - CIBINONG CITY MALL",
      "HAUS! - INDRAPRASTA",
      "HAUS! - KOTA WISATA",
      "HAUS! - TAMAN YASMIN",
      "HAUS! - CIOMAS",
      "HAUS! - CITRA INDAH CITY",
      "HAUS! - CIAPUS",
      "HAUS! - DURIAN RAYA",
      "HAUS! - SUKAHATI",
      "HAUS! - POMAD BOGOR",
      "HAUS! - SURYA KENCANA",
      "HAUS! - CIKARET CIBINONG",
    ],
    CIKARANG: [
      "HAUS! - GRAHA ASRI",
      "HAUS! - INDUSTRI CIKARANG",
      "HAUS! - TARUM BARAT CIKARANG",
    ],
    CILEGON: ["HAUS! - TEMU PUTIH"],
    CIREBON: [
      "HAUS! - CIREMAI",
      "HAUS! - PERJUANGAN",
      "HAUS! - CIREBON SUPER BLOCK",
      "HAUS! - SHELL KESAMBI",
      "HAUS! - KUTAGARA",
    ],
    DEPOK: [
      "HAUS! - GUNADARMA",
      "HAUS! - BEJI",
      "HAUS! - PEKAPURAN",
      "HAUS! - SENTOSA",
      "HAUS! - KEADILAN",
      "HAUS! - SAWANGAN",
      "HAUS! - PITARA",
      "HAUS! - GRAND DEPOK CITY",
      "HAUS! - CITAYAM",
      "HAUS! - MEKARSARI CIMANGGIS",
      "HAUS! - PENGASINAN SAWANGAN",
      "HAUS! - JATIMULYA CILODONG",
      "HAUS! - ITC Depok",
    ],
    GARUT: ["HAUS! - CIMANUK"],
    GRESIK: ["HAUS! - KOTA BARU"],
    JAKARTA: [
      "HAUS! - BINUS 1",
      "HAUS! - PENGUMBEN",
      "HAUS! - TANJUNG GEDONG",
      "HAUS! - MERCU BUANA",
      "HAUS! - PETUKANGAN",
      "HAUS! - MENCENG",
      "HAUS! - PENGGILINGAN",
      "HAUS! - SUMUR BATU",
      "HAUS! - CIBUBUR",
      "HAUS! - JAGAKARSA 1",
      "HAUS! - TEBET",
      "HAUS! - PONDOK KELAPA",
      "HAUS! - BINUS 2",
      "HAUS! - KOTA BAMBU",
      "HAUS! - PANCORAN 2",
      "HAUS! - BUARAN",
      "HAUS! - KALIBATA",
      "HAUS! - PADEMANGAN",
      "HAUS! - KAYU MANIS",
      "HAUS! - HALIM",
      "HAUS! - PASAR RUMPUT",
      "HAUS! - KOJA",
      "HAUS! - PONDOK LABU",
      "HAUS! - KALISARI",
      "HAUS! - RAYA TENGAH",
      "HAUS! - CIPINANG",
      "HAUS! - KAHFI CIGANJUR",
      "HAUS! - KRESEK KOSAMBI",
      "HAUS! - CIRACAS",
      "HAUS! - JAGAKARSA 2",
      "HAUS! - CILANGKAP",
      "HAUS! - PEJATEN",
      "HAUS! - MERUYA",
      "HAUS! - POLTANGAN",
      "HAUS! - TANAH ABANG",
      "HAUS! - KARBELA",
      "HAUS! - BANGKA",
      "HAUS! - RAWAMANGUN",
      "HAUS! - SEMANAN",
      "HAUS! - CIPETE",
      "HAUS! - CEMPAKA PUTIH",
      "HAUS! - WARAKAS",
      "HAUS! - PLUIT",
      "HAUS! - CITRA GARDEN",
      "HAUS! - GREEN VILLE",
      "HAUS! - PGC",
      "HAUS! - SUNTER",
      "HAUS! - SEASON CITY",
      "HAUS! - SRENGSENG",
      "HAUS! - PONDOK PINANG",
      "HAUS! - RADIO DALAM",
      "HAUS! - GEMPOL RAYA",
      "HAUS! - SUMAGUNG",
      "HAUS! - SARINAH",
      "HAUS! - GANDARIA",
      "HAUS! - SUMUR BOR",
      "HAUS! - PLAZA KALIBATA",
      "HAUS!",
      "HAUS! - JELAMBAR UTAMA",
      "HAUS! - PISANGAN LAMA",
      "HAUS! - CITRA GARDEN 7",
      "HAUS! - TAMAN KOTA KEMBANGAN",
      "HAUS! - STASIUN GAMBIR",
      "HAUS! - CITY PARK",
      "HAUS! - MALL CIJANTUNG",
      "HAUS! - BINUS 3",
    ],
    KARAWANG: [
      "HAUS! - GALUH MAS",
      "HAUS! - TANJUNG MEKAR",
      "HAUS! - CIKAMPEK",
    ],
    PURWAKARTA: ["HAUS! - UPI PURWAKARTA"],
    SEMARANG: ["HAUS! - ANJASMORO", "HAUS! - SARINAH", "HAUS! - GAJAH"],
    SERANG: ["HAUS! - CICERI", "HAUS! - CIKANDE", "HAUS! - LOPANG RAYA"],
    SIDOARJO: [
      "HAUS! - TAMAN PINANG",
      "HAUS! - DELTA SARI",
      "HAUS! - PONDOK JATI",
      "HAUS! - SURAPATI",
    ],
    SUBANG: ["HAUS! - OTISTA"],
    SUKABUMI: [
      "HAUS! - BENTENG",
      "HAUS! - CIKOLE",
      "HAUS! - CIBADAK",
      "HAUS! - CISAAT",
    ],
    SURABAYA: [
      "HAUS! - MULYOSARI",
      "HAUS! - RUNGKUT MADYA",
      "HAUS! - SEMOLOWARU",
      "HAUS! - NGAGELREJO",
      "HAUS! - SIWALANKERTO",
      "HAUS! - WIYUNG",
      "HAUS! - GWALK CIPUTRA",
      "HAUS! - MANUKAN",
      "HAUS! - ROYAL PLAZA",
      "HAUS! - KETINTANG",
      "HAUS! - DUKUH KUPANG",
    ],
    SURAKARTA: [
      "HAUS! - GARUDA MAS",
      "HAUS! - JAYA WIJAYA",
      "HAUS! - SUPOMO",
      "HAUS! - SUTOYO",
      "HAUS! - UNS",
    ],
    TANGERANG: [
      "HAUS! - KARANG TENGAH",
      "HAUS! - CEGER",
      "HAUS! - PANARUB",
      "HAUS! - KUTABUMI",
      "HAUS! - PAMULANG 1",
      "HAUS! - JOMBANG",
      "HAUS! - PORIS",
      "HAUS! - CIPUTAT",
      "HAUS! - BINONG",
      "HAUS! - KARAWACI",
      "HAUS! - REMPOA 2",
      "HAUS! - PAMULANG 2",
      "HAUS! - PARUNG SERAB",
      "HAUS! - SEPATAN",
      "HAUS! - CIRENDEU",
      "HAUS! - CITRA RAYA",
      "HAUS! - PASAR LAMA",
      "HAUS! - ANGGREK LOKA BSD",
      "HAUS! - KELAPA DUA",
      "HAUS! - BINTARO",
      "HAUS! - PURI BETA",
      "HAUS! - GRAHA RAYA",
      "HAUS! - BOJONG NANGKA",
      "HAUS! - TAMAN CIBODAS",
      "HAUS! - BANJAR WIJAYA",
      "HAUS! - BERINGIN RAYA",
      "HAUS! - NUSA LOKA BSD",
      "HAUS! - DUTA GARDEN",
      "HAUS! - VILLA DAGO PAMULANG",
      "HAUS! - GONDRONG CIPONDOH",
      "HAUS! - BUKIT SERUA INDAH",
      "HAUS! - CURUG",
      "HAUS! - TALAGA BASTARI",
      "HAUS! - VILLA TANGERANG INDAH",
      "HAUS! - HASYIM ASHARI",
    ],
    YOGYAKARTA: [
      "HAUS! - KAPTEN TENDEAN",
      "HAUS! - PALAGAN",
      "HAUS! - TAMAN SISWA",
      "HAUS! - GODEAN",
      "HAUS! - KALIURANG",
      "HAUS! - GEJAYAN",
      "HAUS! - JAKAL UII",
      "HAUS! - GLAGAHSARI",
      "HAUS! - SETURAN",
      "HAUS! - MALIOBORO",
    ],
  };

  return (
    <div className="space-y-8 w-screen">
      {Object.keys(storeList).map((city) => (
        <LocationList city={city} cityData={storeList[city]} />
      ))}
    </div>
  );
};

export default LocationIter;
