import { LocationList } from "../../components";

const LocationIter = ({}) => {
  const storeList = {
    BANDUNG: [
      "HAUS! BDG - DIPATIUKUR",
      "HAUS! BDG - GEGER KALONG",
      "HAUS! BDG - UJUNG BERUNG",
      "HAUS! BDG - CIJERAH",
      "HAUS! BDG - KIARA CONDONG",
      "HAUS! BDG - ANTAPANI",
      "HAUS! BDG - CIKUTRA",
      "HAUS! BDG - CIMAHI",
      "HAUS! BDG - METRO",
      "HAUS! BDG - CIBIRU",
      "HAUS! BDG - BALEENDAH",
      "HAUS! BDG - STT TELKOM",
      "HAUS! BDG - BUAH BATU",
      "HAUS! BDG - TAMAN KOPO INDAH",
      "HAUS! BDG - CIBADUYUT",
      "HAUS! BDG - PADALARANG",
      "HAUS! BDG - CIUMBULEUIT",
      "HAUS! BDG - RANCAEKEK",
      "HAUS! BDG - CIMAHI 2",
    ],
    BEKASI: [
      "HAUS! BKS - BINTARA",
      "HAUS! BKS - JATIWARINGIN",
      "HAUS! BKS - TAMBUN",
      "HAUS! BKS - CAMAN",
      "HAUS! BKS - PONDOK UNGU",
      "HAUS! BKS - KARTINI",
      "HAUS! BKS - HANKAM",
      "HAUS! BKS - NUSANTARA",
      "HAUS! BKS - RAWALUMBU",
      "HAUS! BKS - CIBITUNG",
      "HAUS! BKS - KARANG SATRIA",
      "HAUS! BKS - PONDOK UNGU 2",
      "HAUS! BKS - GALAXY",
      "HAUS! BKS - HARAPAN INDAH",
      "HAUS! BKS - KRANGGAN PERMAI",
      "HAUS! BKS - NANGKA RAYA",
      "HAUS! BKS - PURI GADING",
      "HAUS! BKS - JATI KRAMAT RAYA",
      "HAUS! BKS - PATRIOT",
      "HAUS! BKS - PRAMUKA RAWALUMBU",
      "HAUS! DPK - RADEN SANIM",
      "HAUS! BKS - DUKUH ZAMBRUD",
      "HAUS! BKS - MUCHTAR TABRANI",
      "HAUS! BKS - MUTIARA GADING",
      "HAUS! BKS - SUMBER ARTHA BINTARA",
      "HAUS! BKS - KALIABANG",
      "HAUS! BKS - KEMANG RAYA JATICEMPAKA",
      "HAUS! BKS - PLASA CIBUBUR",
    ],
    BOGOR: [
      "HAUS! BGR - CIKEAS",
      "HAUS! BGR - AIR MANCUR",
      "HAUS! BGR - EMPANG BOGOR",
      "HAUS! BGR - KEBON PEDES",
      "HAUS! BGR - MAWAR",
      "HAUS! BGR - CIBINONG",
      "HAUS! BGR - TAJUR",
      "HAUS! BGR - DRAMAGA",
      "HAUS! BGR - CIBINONG CITY MALL",
      "HAUS! BGR - INDRAPRASTA",
      "HAUS! BGR - KOTA WISATA",
      "HAUS! BGR - TAMAN YASMIN",
      "HAUS! BGR - CIOMAS",
      "HAUS! BGR - CITRA INDAH CITY",
      "HAUS! BGR - CIAPUS",
      "HAUS! BGR - DURIAN RAYA",
      "HAUS! BGR - SUKAHATI",
      "HAUS! BGR - POMAD BOGOR",
      "HAUS! BGR - SURYA KENCANA",
      "HAUS! BGR - CIKARET CIBINONG",
    ],
    CIKARANG: [
      "HAUS! CKR - GRAHA ASRI",
      "HAUS! CKR - INDUSTRI CIKARANG",
      "HAUS! CKR - TARUM BARAT CIKARANG",
    ],
    CILEGON: ["HAUS! CLG - TEMU PUTIH"],
    CIREBON: [
      "HAUS! CRB - CIREMAI",
      "HAUS! CRB - PERJUANGAN",
      "HAUS! CRB - CIREBON SUPER BLOCK",
      "HAUS! CRB - SHELL KESAMBI",
      "HAUS! CRB - KUTAGARA",
    ],
    DEPOK: [
      "HAUS! DPK - GUNADARMA",
      "HAUS! DPK - BEJI",
      "HAUS! DPK - PEKAPURAN",
      "HAUS! DPK - SENTOSA",
      "HAUS! DPK - KEADILAN",
      "HAUS! DPK - SAWANGAN",
      "HAUS! DPK - PITARA",
      "HAUS! DPK - GRAND DEPOK CITY",
      "HAUS! DPK - CITAYAM",
      "HAUS! DPK - MEKARSARI CIMANGGIS",
      "HAUS! DPK - PENGASINAN SAWANGAN",
      "HAUS! DPK - JATIMULYA CILODONG",
      "HAUS! DPK - ITC Depok",
    ],
    GARUT: ["HAUS! GRT - CIMANUK"],
    GRESIK: ["HAUS! GSK - KOTA BARU"],

    JAKARTA: [
      "HAUS! JKT - BINUS 1",
      "HAUS! JKT - PENGUMBEN",
      "HAUS! JKT - TANJUNG GEDONG",
      "HAUS! JKT - MERCU BUANA",
      "HAUS! JKT - PETUKANGAN",
      "HAUS! JKT - MENCENG",
      "HAUS! JKT - PENGGILINGAN",
      "HAUS! JKT - SUMUR BATU",
      "HAUS! JKT - CIBUBUR",
      "HAUS! JKT - JAGAKARSA 1",
      "HAUS! JKT - TEBET",
      "HAUS! JKT - PONDOK KELAPA",
      "HAUS! JKT - BINUS 2",
      "HAUS! JKT - KOTA BAMBU",
      "HAUS! JKT - PANCORAN 2",
      "HAUS! JKT - BUARAN",
      "HAUS! JKT - KALIBATA",
      "HAUS! JKT - PADEMANGAN",
      "HAUS! JKT - KAYU MANIS",
      "HAUS! JKT - HALIM",
      "HAUS! JKT - PASAR RUMPUT",
      "HAUS! JKT - KOJA",
      "HAUS! JKT - PONDOK LABU",
      "HAUS! JKT - KALISARI",
      "HAUS! JKT - RAYA TENGAH",
      "HAUS! JKT - CIPINANG",
      "HAUS! JKT - KAHFI CIGANJUR",
      "HAUS! JKT - KRESEK KOSAMBI",
      "HAUS! JKT - CIRACAS",
      "HAUS! JKT - JAGAKARSA 2",
      "HAUS! JKT - CILANGKAP",
      "HAUS! JKT - PEJATEN",
      "HAUS! JKT - MERUYA",
      "HAUS! JKT - POLTANGAN",
      "HAUS! JKT - TANAH ABANG",
      "HAUS! JKT - KARBELA",
      "HAUS! JKT - BANGKA",
      "HAUS! JKT - RAWAMANGUN",
      "HAUS! JKT - SEMANAN",
      "HAUS! JKT - CIPETE",
      "HAUS! JKT - CEMPAKA PUTIH",
      "HAUS! JKT - WARAKAS",
      "HAUS! JKT - PLUIT",
      "HAUS! JKT - CITRA GARDEN",
      "HAUS! JKT - GREEN VILLE",
      "HAUS! JKT - PGC",
      "HAUS! JKT - SUNTER",
      "HAUS! JKT - SEASON CITY",
      "HAUS! JKT - SRENGSENG",
      "HAUS! JKT - PONDOK PINANG",
      "HAUS! JKT - RADIO DALAM",
      "HAUS! JKT - GEMPOL RAYA",
      "HAUS! JKT - SUMAGUNG",
      "HAUS! JKT - SARINAH",
      "HAUS! JKT - GANDARIA",
      "HAUS! JKT - SUMUR BOR",
      "HAUS! JKT - PLAZA KALIBATA",
      "HAUS! EVENT",
      "HAUS! JKT - JELAMBAR UTAMA",
      "HAUS! JKT - PISANGAN LAMA",
      "HAUS! JKT - CITRA GARDEN 7",
      "HAUS! JKT - TAMAN KOTA KEMBANGAN",
      "HAUS! JKT - STASIUN GAMBIR",
      "HAUS! JKT - CITY PARK",
      "HAUS! JKT - MALL CIJANTUNG",
      "HAUS! JKT - BINUS 3",
    ],
    KARAWANG: [
      "HAUS! KWG - GALUH MAS",
      "HAUS! KWG - TANJUNG MEKAR",
      "HAUS! KWG - CIKAMPEK",
    ],
    PURWAKARTA: ["HAUS! PWK - UPI PURWAKARTA"],
    SEMARANG: [
      "HAUS! SMG - ANJASMORO",
      "HAUS! SMG - SARINAH",
      "HAUS! SMG - GAJAH",
    ],
    SERANG: [
      "HAUS! SRG - CICERI",
      "HAUS! SRG - CIKANDE",
      "HAUS! SRG - LOPANG RAYA",
    ],
    SIDOARJO: [
      "HAUS! SDA - TAMAN PINANG",
      "HAUS! SDA - DELTA SARI",
      "HAUS! SDA - PONDOK JATI",
      "HAUS! SDA - SURAPATI",
    ],
    SUBANG: ["HAUS! SBG - OTISTA"],
    SUKABUMI: [
      "HAUS! SKB - BENTENG",
      "HAUS! SKB - CIKOLE",
      "HAUS! SKB - CIBADAK",
      "HAUS! SKB - CISAAT",
    ],
    SURABAYA: [
      "HAUS! SBY - MULYOSARI",
      "HAUS! SBY - RUNGKUT MADYA",
      "HAUS! SBY - SEMOLOWARU",
      "HAUS! SBY - NGAGELREJO",
      "HAUS! SBY - SIWALANKERTO",
      "HAUS! SBY - WIYUNG",
      "HAUS! SBY - GWALK CIPUTRA",
      "HAUS! SBY - MANUKAN",
      "HAUS! SBY - ROYAL PLAZA",
      "HAUS! SBY - KETINTANG",
      "HAUS! SBY - DUKUH KUPANG",
    ],
    SURAKARTA: [
      "HAUS! SKT - GARUDA MAS",
      "HAUS! SKT - JAYA WIJAYA",
      "HAUS! SKT - SUPOMO",
      "HAUS! SKT - SUTOYO",
      "HAUS! SKT - UNS",
    ],
    TANGERANG: [
      "HAUS! TNG - KARANG TENGAH",
      "HAUS! TNG - CEGER",
      "HAUS! TNG - PANARUB",
      "HAUS! TNG - KUTABUMI",
      "HAUS! TNG - PAMULANG 1",
      "HAUS! TNG - JOMBANG",
      "HAUS! TNG - PORIS",
      "HAUS! TNG - CIPUTAT",
      "HAUS! TNG - BINONG",
      "HAUS! TNG - KARAWACI",
      "HAUS! TNG - REMPOA 2",
      "HAUS! TNG - PAMULANG 2",
      "HAUS! TNG - PARUNG SERAB",
      "HAUS! TNG - SEPATAN",
      "HAUS! TNG - CIRENDEU",
      "HAUS! TNG - CITRA RAYA",
      "HAUS! TNG - PASAR LAMA",
      "HAUS! TNG - ANGGREK LOKA BSD",
      "HAUS! TNG - KELAPA DUA",
      "HAUS! TNG - BINTARO",
      "HAUS! TNG - PURI BETA",
      "HAUS! TNG - GRAHA RAYA",
      "HAUS! TNG - BOJONG NANGKA",
      "HAUS! TNG - TAMAN CIBODAS",
      "HAUS! TNG - BANJAR WIJAYA",
      "HAUS! TNG - BERINGIN RAYA",
      "HAUS! TNG - NUSA LOKA BSD",
      "HAUS! TNG - DUTA GARDEN",
      "HAUS! TNG - VILLA DAGO PAMULANG",
      "HAUS! TNG - GONDRONG CIPONDOH",
      "HAUS! TNG - BUKIT SERUA INDAH",
      "HAUS! TNG - CURUG",
      "HAUS! TNG - TALAGA BASTARI",
      "HAUS! TNG - VILLA TANGERANG INDAH",
      "HAUS! TNG - HASYIM ASHARI",
    ],
    YOGYAKARTA: [
      "HAUS! YYK - KAPTEN TENDEAN",
      "HAUS! YYK - PALAGAN",
      "HAUS! YYK - TAMAN SISWA",
      "HAUS! YYK - GODEAN",
      "HAUS! YYK - KALIURANG",
      "HAUS! YYK - GEJAYAN",
      "HAUS! YYK - JAKAL UII",
      "HAUS! YYK - GLAGAHSARI",
      "HAUS! YYK - SETURAN",
      "HAUS! YYK - MALIOBORO",
    ],
  };

  return (
    <div className="space-y-8">
      {Object.keys(storeList).map((city) => (
        <LocationList city={city} cityData={storeList[city]} />
      ))}
    </div>
  );
};

export default LocationIter;
